# syntax=docker/dockerfile:1
FROM golang:1.24-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY cmd ./cmd
COPY engine ./engine
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/server ./cmd

FROM alpine:latest
COPY --from=build /out/server /app/server
WORKDIR /data
EXPOSE 8080
ENTRYPOINT ["/app/server", "-server"]
